export const FETCH_USER = 'fetch_user';

export default {
    FETCH_USER: 'fetch_user',
    GET_USER_DATA: 'get_user_data',
    UPDATE_BINDER_ARRAY: 'update_binder_array',
    AXIOS_ERROR: 'axios_error',
    ADD_BINDER: 'add_binder',
    ADD_TAB: 'add_tab',
    ADD_PAGE: 'add_page',
    DELETE_BINDER: 'delete_binder',
    DELETE_TAB: 'delete_tab',
    DELETE_PAGE: 'delete_page',
    EDIT_BINDER: 'edit_binder',
    EDIT_TAB: 'edit_tab',
    EDIT_PAGE: 'edit_page',
    SELECT_BINDER: 'select_binder',
    SELECT_TAB: 'select_tab',
    SELECT_PAGE: 'select_page',
    UPDATE_BINDER_OBJ: 'update_binder_obj',
    GET_VIDEO_RESULTS: 'get_video_results',
    SET_VIDEO_URL: 'set_video_url',
    PLAY_PASTED_VIDEO_LINK: 'play_pasted_video',
    PLAY_VIDEO: 'play_video',
    ADD_TO_PLAYLIST: 'add_to_playlist',
    GET_RESULT_STYLES: 'get_result_styles',
    GET_OPACITY_DISPLAY: 'get_opacity_display',
    TOGGLE_RESULTS: 'toggle_results',
    TOGGLE_MODAL: 'toggle_modal',
    TOGGLE_VIDEO_SLIDE_OUT: 'toggle_video_slide_out',
    EMPTY_VIDEO_SLIDE_OUT: 'empty_video_slide_out',
    GRAB_VIDEO_URL: 'grab_video_url',
    SET_SLIDES_URL: 'set_slides_url',
    GET_SLIDES_URL: 'get_slides_url',
    RESET_SLIDES_URL: 'reset_slides_url',
    SAVE_NOTES: 'save_notes',
    PANEL_TOP_LEFT_HEIGHT: 'panel_top_left_height',
    PANEL_TOP_LEFT_WIDTH: 'panel_top_left_width',
    PANEL_TOP_RIGHT_HEIGHT: 'panel_top_right_height',
    NUM_OF_PANELS: 'num_of_panels',
    GET_PANEL_NUM: 'get_panel_num',
    RESET_PANEL_NUM: 'reset_panel_num',
    NO_VIDEO_LINK: 'no_video_link',
    HIDE_NAV: 'hide_nav',
    SHOW_NAV: 'show_nav',
    EDITABLE: 'editable',
    NOT_EDITABLE: 'not_editable'
}